version: "3"
services:
  nginx:
    image: nginx:alpine #镜像
    ports:
      - "80:80" #端口映射 本地：容器
      - "433:433"
    privileged: true #使容器内的root账户拥有root权限（之前只是普通用户权限）
    volumes: #文件映射
      - ./www:/var/www/html/:rw #项目地址
      - ./conf/conf.d:/etc/nginx/conf.d/:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf/:rw
      - ./log:/var/log/nginx/:rw
    restart: always #重启方式
    networks:
        - default
    links: #指定别名链接其他服务中的容器
        - php72:fpm72

  php72:
    build:
      context: .
      args:
        PHP_VERSION: 7.2.13
        PHP_REDIS: 4.1.1
        REPLACE_SOURCE_LIST: true
    ports:    
      - "9010:9000"
    privileged: true
    volumes:
      - ./www:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
    links:
        - mysql:mysql

  mysql:
    image: mariadb:10.4.5-bionic
    ports:
      - "3306:3306"
    privileged: true  
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

networks:
  default:      
